-- This is my keybindings file.
-- The basics:
vim.keymap.set("i", "nnn", "<Esc>")
vim.keymap.set("n", ";", ":")
vim.keymap.set("n", "<M-m>", "h", { noremap = true })
vim.keymap.set("n", "<M-n>", "gj")
vim.keymap.set("n", "<M-e>", "gk")
vim.keymap.set("n", "<M-i>", "l", { noremap = true })
vim.keymap.set("v", "<M-m>", "h", { noremap = true })
vim.keymap.set("v", "<M-n>", "gj")
vim.keymap.set("v", "<M-e>", "gk")
vim.keymap.set("v", "<M-i>", "l", { noremap = true })
vim.keymap.set("n", "<M-Up>", ":TmuxNavigateUp<CR>")
vim.keymap.set("n", "<M-Down>", ":TmuxNavigateDown<CR>")
vim.keymap.set("n", "<M-Left>", ":TmuxNavigateLeft<CR>")
vim.keymap.set("n", "<M-Right>", ":TmuxNavigateRight<CR>")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "j", "q", { noremap = true })
vim.keymap.set("n", "q", "b")
vim.keymap.set("n", "f", "e")
vim.keymap.set("n", "t", "f", { noremap = true })
vim.keymap.set("n", "<leader>ba", ":badd ")
vim.keymap.set("n", "<leader>bd", ":bd<CR>")
-- Obsidian
vim.keymap.set("n", "<leader>ob", ":VimwikiBacklinks<CR>")
vim.keymap.set("n", "<leader>os", ":VimwikiSearch<CR>")
vim.keymap.set("n", "<leader>ol", ":Oil<CR>")
vim.keymap.set("n", "<S-CR>", ":VimwikiUISelect<CR>")
vim.keymap.set("i", "---", "—")
vim.keymap.set("i", "...", "…")
